USE [master]
GO

/****** Object:  Database [CHESSDB]    Script Date: 05/30/2012 19:24:24 ******/
CREATE DATABASE [CHESSDB] ON  PRIMARY 
( NAME = N'CHESSDB', FILENAME = N'S:\Works\Codename Game Warden\Chess Warden\CHESSDB.mdf' , SIZE = 29696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CHESSDB_log', FILENAME = N'S:\Works\Codename Game Warden\Chess Warden\CHESSDB_log.ldf' , SIZE = 15040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CHESSDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHESSDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CHESSDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CHESSDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CHESSDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CHESSDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CHESSDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CHESSDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CHESSDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CHESSDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CHESSDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CHESSDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CHESSDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CHESSDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CHESSDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CHESSDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CHESSDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CHESSDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CHESSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CHESSDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CHESSDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CHESSDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CHESSDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CHESSDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CHESSDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CHESSDB] SET  READ_WRITE 
GO

ALTER DATABASE [CHESSDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CHESSDB] SET  MULTI_USER 
GO

ALTER DATABASE [CHESSDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CHESSDB] SET DB_CHAINING OFF 
GO

